[package]
name = "serviceless-actor"
version = "0.5.0"
edition = "2021"
description = "An simple actor model in rust, like actix"
license = "MIT"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
futures-util = { workspace = true }
futures-core = { workspace = true }
