[package]
name = "serviceless-core"
version = "0.1.0"
edition = "2021"
description = "An simple actor model in rust, like actix"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
